export interface CreativeBrief {
  id?: string;
  title: string;
  objective: string;
  targetAudience: string;
  keyMessage: string;
  tone: string;
  callToAction: string;
  constraints?: string[];
  references?: string[];
  sourceVideoUrl?: string;
  createdAt?: string;
}

export interface ScriptOutline {
  scenes: ScriptScene[];
  totalDurationEstimate?: number;
}

export interface ScriptScene {
  order: number;
  hook: string;
  body: string;
  cta: string;
  durationSeconds?: number;
}

/** Detailed script from SCRIPT_OUTLINE_PROMPT (Claude). */
export interface GeneratedScriptOutline {
  total_duration_seconds: number;
  scenes: Array<{
    scene_number: number;
    duration_seconds: number;
    type: string;
    visual_description: string;
    audio_text: string;
    text_overlay: string;
    music_mood: string;
    notes: string;
  }>;
  overall_notes: string;
  hashtag_suggestions: string[];
  posting_time_suggestion: string;
}

/** Brief generated by BriefGenerator (saved to briefs table). */
export interface GeneratedBrief {
  id: string;
  project_id: string;
  client_id: string;
  user_id: string;
  title: string;
  objective: string;
  target_audience: string;
  key_insight: string;
  hook_suggestions: Array<{ hook_text: string; hook_type: string; rationale: string; reference_video_id: string | null }>;
  content_directions: Array<{ direction: string; rationale: string; format_suggestion: string; estimated_performance?: string }>;
  script_outline: string;
  tone_guidance: string;
  do_list: string[];
  dont_list: string[];
  reference_video_ids: string[];
  status: 'draft' | 'review' | 'approved';
  generated_at: string;
  model_used: string;
  token_count: number | null;
  script_outline_detail: GeneratedScriptOutline | null;
  version?: number;
}
